#ifndef _LOCAL_HAL_CONF_H
#define _LOCAL_HAL_CONF_H

#define UART_LIDAR_LD20                USART6
#define UART_LIDAR_LD20_CLK_ENABLE     __HAL_RCC_USART6_CLK_ENABLE
#define UART_LIDAR_LD20_DMA_CLK_ENABLE __HAL_RCC_DMA1_CLK_ENABLE

#define DMA_LIDAR_LD20_IRQ        DMA1_Stream0_IRQn
#define LIDAR_LD20_DMA_IRQHandler DMA1_Stream0_IRQHandler
#define DMA_LIDAR_LD20_STREAM     DMA1_Stream0
//define DMA_LIDAR_LD20_CHANNEL     DMA_CHANNEL_4
#define DMA_LIDAR_LD20_REQUEST    DMA_REQUEST_USART6_RX

#define UART_LIDAR_LD20_GPIO GpioG
#define UART_LIDAR_LD20_GPIO_PINS ( BIT9 | BIT14 )
#define UART_LIDAR_LD20_GPIO_AF GPIO_AF7_USART6

#define HAL_UART_USERINIT_FUN HAL_UART_UserInit

int MX_LIDAR_LD20_UART_Init(void);
void MX_LIDAR_LD20_DMA_Init(void);
// void HAL_UART_UserInit( UART_HandleTypeDef* uartHandle );


#endif

