# SRCS += stm32f1xx_hal_adc.c
# SRCS += stm32f1xx_hal_adc_ex.c
# SRCS += stm32f1xx_hal_can.c
# SRCS += stm32f1xx_hal_cec.c
# SRCS += stm32f1xx_hal_crc.c
# SRCS += stm32f1xx_hal_dac.c
# SRCS += stm32f1xx_hal_dac_ex.c
# SRCS += stm32f1xx_hal_dma.c
# SRCS += stm32f1xx_hal_eth.c
# SRCS += stm32f1xx_hal_flash.c
# SRCS += stm32f1xx_hal_flash_ex.c
# SRCS += stm32f1xx_hal_gpio_ex.c
# SRCS += stm32f1xx_hal_hcd.c
# SRCS += stm32f1xx_hal_i2c.c
# SRCS += stm32f1xx_hal_i2s.c
# SRCS += stm32f1xx_hal_irda.c
# SRCS += stm32f1xx_hal_iwdg.c
# SRCS += stm32f1xx_hal_nand.c
# SRCS += stm32f1xx_hal_nor.c
# SRCS += stm32f1xx_hal_pccard.c
# SRCS += stm32f1xx_hal_pcd.c
# SRCS += stm32f1xx_hal_pcd_ex.c
# SRCS += stm32f1xx_hal_pwr.c
# SRCS += stm32f1xx_hal_rcc_ex.c
# SRCS += stm32f1xx_hal_rtc.c
# SRCS += stm32f1xx_hal_rtc_ex.c
# SRCS += stm32f1xx_hal_sd.c
# SRCS += stm32f1xx_hal_smartcard.c
# SRCS += stm32f1xx_hal_spi.c
# SRCS += stm32f1xx_hal_spi_ex.c
# SRCS += stm32f1xx_hal_sram.c
# SRCS += stm32f1xx_hal_tim.c
# SRCS += stm32f1xx_hal_tim_ex.c
# SRCS += stm32f1xx_hal_uart.c
# SRCS += stm32f1xx_hal_usart.c
# SRCS += stm32f1xx_hal_wwdg.c

# added by default
# SRCS += stm32f1xx_hal.c
# SRCS += stm32f1xx_hal_cortex.c
# SRCS += stm32f1xx_hal_gpio.c
# SRCS += stm32f1xx_hal_rcc.c

# low-level
# SRCS += stm32f1xx_ll_fsmc.c
# SRCS += stm32f1xx_ll_sdmmc.c
# SRCS += stm32f1xx_ll_usb.c
