" uses definitions from cpp_stl2.vim from Mizuchi <ytj000@gmail.com>

hi oxcMacro         gui=bold   guifg=#661111
hi oxcTypeAlias     gui=bold   guifg=#005500
hi oxcBaseType      gui=bold   guifg=#006611
hi oxcBaseCap       gui=bold   guifg=#555511
hi oxcCnvType       gui=bold   guifg=#001155
hi oxcRoboChannel   gui=bold   guifg=#004444
hi oxcImmedCap      gui=bold   guifg=#001177
hi oxcRoboCap       gui=bold   guifg=#004477
hi oxcRoboType      gui=bold   guifg=#009944
hi oxcHwDev         gui=bold   guifg=#000033
hi oxcConstant                 guifg=#990055
hi oxcIO                       guifg=#111199
hi oxcFunction                 guifg=#004444

syntax keyword oxcMacro DCL_CMD_REG
syntax keyword oxcMacro USE_DIE_ERROR_HANDLER
syntax keyword oxcMacro USE_DIE4LED_ERROR_HANDLER
syntax keyword oxcMacro USE_DIE_EXIT
syntax keyword oxcMacro USE_DIE4LED_EXIT
syntax keyword oxcMacro BOARD_DEFINE_LEDS
syntax keyword oxcMacro BOARD_CONSOLE_DEFINES
syntax keyword oxcMacro BOARD_PROLOG
syntax keyword oxcMacro BOARD_POST_INIT_BLINK
syntax keyword oxcMacro TO_MACRO_STR
syntax keyword oxcMacro OXC_PASTER2
syntax keyword oxcMacro OXC_PASTER3
syntax keyword oxcMacro OXC_PASTER4
syntax keyword oxcMacro OXC_EVAL2
syntax keyword oxcMacro OXC_EVAL3
syntax keyword oxcMacro OXC_EVAL4
syntax keyword oxcMacro AUX_TICK_FUN_N
syntax keyword oxcMacro TASK_LEDS_QUANT
syntax keyword oxcMacro GET_OS_TICK
syntax keyword oxcMacro CMD_FUNCTION
syntax keyword oxcMacro DEFINE_TIMER_DATA
syntax keyword oxcMacro DEFINE_TIMER_DATA_PWM1
syntax keyword oxcMacro DEFINE_TIMER_DATA_PWM1_1P
syntax keyword oxcMacro DEFINE_TIMER_DATA_PWM1_2P
syntax keyword oxcMacro DEFINE_TIMER_DATA_ENCO
syntax keyword oxcMacro DEFINE_NAMEDOBJ_FUNCS
syntax keyword oxcMacro SET_NAMEDOBJ_FUNCS


syntax keyword oxcTypeAlias xfloat
syntax keyword oxcTypeAlias ReturnCode
syntax keyword oxcTypeAlias byte_span
syntax keyword oxcTypeAlias cbyte_span
syntax keyword oxcTypeAlias char_span
syntax keyword oxcTypeAlias cchar_span
syntax keyword oxcTypeAlias int_span
syntax keyword oxcTypeAlias cint_span
syntax keyword oxcTypeAlias int16_t_span
syntax keyword oxcTypeAlias cint16_t_span
syntax keyword oxcTypeAlias uint16_t_span
syntax keyword oxcTypeAlias cuint16_t_span
syntax keyword oxcTypeAlias int32_t_span
syntax keyword oxcTypeAlias cint32_t_span
syntax keyword oxcTypeAlias uint32_t_span
syntax keyword oxcTypeAlias cuint32_t_span
syntax keyword oxcTypeAlias float_span
syntax keyword oxcTypeAlias cfloat_span
syntax keyword oxcTypeAlias int_t_er
syntax keyword oxcTypeAlias uint_t_er
syntax keyword oxcTypeAlias int8_t_er
syntax keyword oxcTypeAlias uint8_t_er
syntax keyword oxcTypeAlias int16_t_er
syntax keyword oxcTypeAlias uint16_t_er
syntax keyword oxcTypeAlias int32_t_er
syntax keyword oxcTypeAlias uint32_t_er
syntax keyword oxcTypeAlias int64_t_er
syntax keyword oxcTypeAlias uint64_t_er
syntax keyword oxcTypeAlias float_er
syntax keyword oxcTypeAlias int_t_o
syntax keyword oxcTypeAlias uint_t_o
syntax keyword oxcTypeAlias int8_t_o
syntax keyword oxcTypeAlias uint8_t_o
syntax keyword oxcTypeAlias int16_t_o
syntax keyword oxcTypeAlias uint16_t_o
syntax keyword oxcTypeAlias int32_t_o
syntax keyword oxcTypeAlias uint32_t_o
syntax keyword oxcTypeAlias int64_t_o
syntax keyword oxcTypeAlias uint64_t_o
syntax keyword oxcTypeAlias float_o
syntax keyword oxcTypeAlias TickType
syntax keyword oxcTypeAlias run_periodic_fun


syntax keyword oxcBaseType GpioModer
syntax keyword oxcBaseType GpioPull
syntax keyword oxcBaseType ExtiEv
syntax keyword oxcBaseType GpioRegs
syntax keyword oxcBaseType PinMask
syntax keyword oxcBaseType PinNum
syntax keyword oxcBaseType PortPin
syntax keyword oxcBaseType Pins
syntax keyword oxcBaseType PinOut
syntax keyword oxcBaseType PinsOut
syntax keyword oxcBaseType PinsIn
syntax keyword oxcBaseType IoPin
syntax keyword oxcBaseType EXTI_init_info
syntax keyword oxcBaseType BitNames
syntax keyword oxcBaseType CStr
syntax keyword oxcBaseType RunLoopData
syntax keyword oxcBaseType RunLoopState
syntax keyword oxcBaseType ADC_Info
syntax keyword oxcBaseType AdcChannelInfo
syntax keyword oxcBaseType AdcSampleTimeInfo
syntax keyword oxcBaseType ADC_freq_info
syntax keyword oxcBaseType AdcData
syntax keyword oxcBaseType ADS1115
syntax keyword oxcBaseType AS5600
syntax keyword oxcBaseType AutoIncDec
syntax keyword oxcBaseType RestoreAtLeave
syntax keyword oxcBaseType DoAtLeave
syntax keyword oxcBaseType BMP085
syntax keyword oxcBaseType BMP280
syntax keyword oxcBaseType DevIO
syntax keyword oxcBaseType DS3231
syntax keyword oxcBaseType EasingFun
syntax keyword oxcBaseType HD44780_i2c
syntax keyword oxcBaseType HMC5983
syntax keyword oxcBaseType HX711
syntax keyword oxcBaseType DevI2C
syntax keyword oxcBaseType I2CClient
syntax keyword oxcBaseType INA226
syntax keyword oxcBaseType INA228
syntax keyword oxcBaseType MCP23017
syntax keyword oxcBaseType MCP4725
syntax keyword oxcBaseType RD6006_Modbus
syntax keyword oxcBaseType MODBUS_RTU_server
syntax keyword oxcBaseType MPU6050
syntax keyword oxcBaseType Mu_t
syntax keyword oxcBaseType NamedFloat
syntax keyword oxcBaseType NamedObj
syntax keyword oxcBaseType NamedInt
syntax keyword oxcBaseType NamedObjs
syntax keyword oxcBaseType NamedSubObj
syntax keyword oxcBaseType OneWire
syntax keyword oxcBaseType OutStr
syntax keyword oxcBaseType OutStream
syntax keyword oxcBaseType PCA9685
syntax keyword oxcBaseType PCD8544
syntax keyword oxcBaseType PCF8591
syntax keyword oxcBaseType PixBuf
syntax keyword oxcBaseType PixBuf1V
syntax keyword oxcBaseType RingBuf
syntax keyword oxcBaseType RoboDevice
syntax keyword oxcBaseType SensorBase
syntax keyword oxcBaseType ActuatorLimits
syntax keyword oxcBaseType Gpio_Pin_Dev

syntax keyword oxcBaseType RtosQueue
syntax keyword oxcBaseType EncoderEng
syntax keyword oxcBaseType SmallRL
syntax keyword oxcBaseType DevSPI
syntax keyword oxcBaseType DevAD9833
syntax keyword oxcBaseType ADS1220
syntax keyword oxcBaseType DevSPI_DAC8563
syntax keyword oxcBaseType DevSPI_MAX7219
syntax keyword oxcBaseType DevSPIMem_AT
syntax keyword oxcBaseType SSD1306
syntax keyword oxcBaseType StatChannel
syntax keyword oxcBaseType StatChannelXY
syntax keyword oxcBaseType RegreResults
syntax keyword oxcBaseType StatData
syntax keyword oxcBaseType OxcTicker
syntax keyword oxcBaseType PwmCh
syntax keyword oxcBaseType TIM_TypeDef
syntax keyword oxcBaseType TIM_HandleTypeDef
syntax keyword oxcBaseType TIM_OC_InitTypeDef
syntax keyword oxcBaseType TIM_ClockConfigTypeDef
syntax keyword oxcBaseType TIM_Encoder_InitTypeDef
syntax keyword oxcBaseType TIM_MasterConfigTypeDef
syntax keyword oxcBaseType UsartIO
syntax keyword oxcBaseType UsbcdcIO
syntax keyword oxcBaseType UT61E_package

syntax keyword oxcCnvType TransFF
syntax keyword oxcCnvType TransFI
syntax keyword oxcCnvType TransIF
syntax keyword oxcCnvType TransII
syntax keyword oxcCnvType TransFFUnity
syntax keyword oxcCnvType TransFFLin
syntax keyword oxcCnvType TransFFLinLim
syntax keyword oxcCnvType TransFIUnity
syntax keyword oxcCnvType TransFILin
syntax keyword oxcCnvType TransFILinRound
syntax keyword oxcCnvType TransFILinLim
syntax keyword oxcCnvType TransIFUnity
syntax keyword oxcCnvType TransIFLin
syntax keyword oxcCnvType TransIIUnity
syntax keyword oxcCnvType TransIILin

syntax keyword oxcRoboChannel OutChFBase
syntax keyword oxcRoboChannel OutChFNull
syntax keyword oxcRoboChannel OutChFProxy
syntax keyword oxcRoboChannel OutChFSplit2
syntax keyword oxcRoboChannel OutChF
syntax keyword oxcRoboChannel OutChFF
syntax keyword oxcRoboChannel OutChFI
syntax keyword oxcRoboChannel OutChIBase
syntax keyword oxcRoboChannel OutChINull
syntax keyword oxcRoboChannel OutChIProxy
syntax keyword oxcRoboChannel OutChISplit2
syntax keyword oxcRoboChannel OutChI
syntax keyword oxcRoboChannel OutChIF
syntax keyword oxcRoboChannel OutChII
syntax keyword oxcRoboChannel InChFBase
syntax keyword oxcRoboChannel InChFConst
syntax keyword oxcRoboChannel InChFProxy
syntax keyword oxcRoboChannel InChFSum2
syntax keyword oxcRoboChannel InChFFun2
syntax keyword oxcRoboChannel InChF
syntax keyword oxcRoboChannel InChFF
syntax keyword oxcRoboChannel InChFI
syntax keyword oxcRoboChannel InChIBase
syntax keyword oxcRoboChannel InChIConst
syntax keyword oxcRoboChannel InChIProxy
syntax keyword oxcRoboChannel InChISum2
syntax keyword oxcRoboChannel InChI
syntax keyword oxcRoboChannel InChIF
syntax keyword oxcRoboChannel InChII

syntax keyword oxcBaseCap PinPureCapability
syntax keyword oxcBaseCap PinsPureCapability
syntax keyword oxcBaseCap PwmPureCapability
syntax keyword oxcBaseCap PwmBaseBasic
syntax keyword oxcBaseCap EncoderPureCapability
syntax keyword oxcBaseCap AdcDacPureCapability
syntax keyword oxcBaseCap AdcPureCapability
syntax keyword oxcBaseCap DacPureCapability
syntax keyword oxcBaseCap IoCapability
syntax keyword oxcBaseCap RoboObject
syntax keyword oxcBaseCap IoRoboCapability

syntax keyword oxcImmedCap PinsCapability
syntax keyword oxcImmedCap PinCapability
syntax keyword oxcImmedCap PwmCapability
syntax keyword oxcImmedCap EncoderCapability
syntax keyword oxcImmedCap AdcDacCapability
syntax keyword oxcImmedCap AdcCapability
syntax keyword oxcImmedCap DacCapability

syntax keyword oxcRoboCap PinsRoboCapability
syntax keyword oxcRoboCap PinRoboCapability
syntax keyword oxcRoboCap PwmRoboCapability
syntax keyword oxcRoboCap EncoderRoboCapability
syntax keyword oxcRoboCap AdcDacRoboCapability
syntax keyword oxcRoboCap AdcRoboCapability
syntax keyword oxcRoboCap DacRoboCapability

syntax keyword oxcRoboType RoboJointCtl
syntax keyword oxcRoboType RoboJointCtlPos
syntax keyword oxcRoboType RoboJoint
syntax keyword oxcRoboType RoboAssembly

syntax keyword oxcHwDev Addr_Enco_Dev
syntax keyword oxcHwDev Gpio_Pin_Dev
syntax keyword oxcHwDev Gpio_Pins_Dev
syntax keyword oxcHwDev Tim_Pwm_Dev
syntax keyword oxcHwDev Adcint_Adc_Dev
syntax keyword oxcHwDev Dacint_Dac_Dev

syntax keyword oxcIO  std_out
syntax keyword oxcIO  OUT
syntax keyword oxcIO  FmtInt
syntax keyword oxcIO  FltFmt
syntax keyword oxcIO  HexInt
syntax keyword oxcIO  HexInt64
syntax keyword oxcIO  HexInt16
syntax keyword oxcIO  HexInt8
syntax keyword oxcIO  FntUns
syntax keyword oxcIO  FixedPoint1
syntax keyword oxcIO  FixedPoint2
syntax keyword oxcIO  FloatMult
syntax keyword oxcIO  BitsStr
syntax keyword oxcIO  OSTR

syntax match   oxcConstant 'UVAR_[a-z]'
syntax match   oxcConstant '\<P[A-M]\d\+\>'
syntax match   oxcConstant 'TIM_CHANNEL_\d'
syntax match   oxcConstant 'TimCh\d'
syntax match   oxcConstant '\<BIT\d\+\>'
syntax match   oxcConstant '\<BIT\d\+M\>'
syntax keyword oxcConstant NL
syntax keyword oxcConstant BAD_ADDR
syntax keyword oxcConstant rcOk
syntax keyword oxcConstant rcWarn
syntax keyword oxcConstant rcEnd
syntax keyword oxcConstant rcErr
syntax keyword oxcConstant rcFatal
syntax keyword oxcConstant pi_f
syntax keyword oxcConstant pi_d2_f
syntax keyword oxcConstant inv_pi_f
syntax keyword oxcConstant rad2deg_k_f
syntax keyword oxcConstant deg2rad_k_f
syntax keyword oxcConstant TimCh1
syntax keyword oxcConstant TimCh2
syntax keyword oxcConstant TimCh3
syntax keyword oxcConstant TimCh4
syntax keyword oxcConstant TimCh5
syntax keyword oxcConstant TimCh6
syntax keyword oxcConstant TimCh7
syntax keyword oxcConstant TimCh8
syntax keyword oxcConstant TimChPin

syntax keyword oxcFunction arg2float_d
syntax keyword oxcFunction arg2long_d
syntax keyword oxcFunction arg2T
syntax keyword oxcFunction arg2ulong_d
syntax keyword oxcFunction bcd_to_char2
syntax keyword oxcFunction bcd_to_uint8
syntax keyword oxcFunction char2hex
syntax keyword oxcFunction d2r
syntax keyword oxcFunction delay_bad_100ns
syntax keyword oxcFunction delay_bad_mcs
syntax keyword oxcFunction delay_bad_ms
syntax keyword oxcFunction delay_bad_n
syntax keyword oxcFunction delay_bad_s
syntax keyword oxcFunction delay_mcs
syntax keyword oxcFunction delay_ms
syntax keyword oxcFunction delay_ms_brk
syntax keyword oxcFunction delay_ms_until_brk
syntax keyword oxcFunction delay_ms_until_brk_ex
syntax keyword oxcFunction die
syntax keyword oxcFunction die4led
syntax keyword oxcFunction do_delay_calibrate
syntax keyword oxcFunction dump32
syntax keyword oxcFunction dump8
syntax keyword oxcFunction exp10i
syntax keyword oxcFunction i2dec
syntax keyword oxcFunction i2dec_n
syntax keyword oxcFunction ifcvt
syntax keyword oxcFunction imax
syntax keyword oxcFunction imin
syntax keyword oxcFunction init_uart
syntax keyword oxcFunction isNameChar
syntax keyword oxcFunction isNameChar1
syntax keyword oxcFunction Mu_init
syntax keyword oxcFunction Mu_lock
syntax keyword oxcFunction Mu_tryloc
syntax keyword oxcFunction Mu_unlock
syntax keyword oxcFunction numFirstBit
syntax keyword oxcFunction on_delay_actions
syntax keyword oxcFunction oxc_add_aux_tick_fun
syntax keyword oxcFunction oxc_call_aux_tick_funcs
syntax keyword oxcFunction oxc_clear_aux_tick_funs
syntax keyword oxcFunction oxc_del_aux_tick_fun
syntax keyword oxcFunction pow2
syntax keyword oxcFunction pow2f
syntax keyword oxcFunction r2d
syntax keyword oxcFunction rev16
syntax keyword oxcFunction rev32
syntax keyword oxcFunction run_periodic
syntax keyword oxcFunction short2hex
syntax keyword oxcFunction sign
syntax keyword oxcFunction signf
syntax keyword oxcFunction signxf
syntax keyword oxcFunction skip_ws
syntax keyword oxcFunction specstr2v
syntax keyword oxcFunction SPI_init_default
syntax keyword oxcFunction splitNameWithIdx
syntax keyword oxcFunction strtoT
syntax keyword oxcFunction u2_3dig
syntax keyword oxcFunction u2dec_n
syntax keyword oxcFunction u64_2hex
syntax keyword oxcFunction uint8_to_bcd
syntax keyword oxcFunction word2hex


