#ifndef _LOCAL_HAL_CONF_H
#define _LOCAL_HAL_CONF_H

#define UART_MODBUS USART1
#define UART_MODBUS_CLK_ENABLE __HAL_RCC_USART1_CLK_ENABLE
#define UART_MODBUS_GPIO GpioA
#define UART_MODBUS_PIN_TX PA9
#define UART_MODBUS_PIN_RX PA10
#define UART_MODBUS_GPIO_AF GPIO_AF7_USART1
#define UART_MODBUS_IRQ USART1_IRQn
#define UART_MODBUS_IRQHANDLER USART1_IRQHandler

#define HAL_UART_USERINIT_FUN HAL_UART_UserInit

int MX_MODBUS_UART_Init(void);

#define TIM_CNT TIM2
#define TIM_CNT_EN    __HAL_RCC_TIM2_CLK_ENABLE();
#define TIM_CNT_DIS   __HAL_RCC_TIM2_CLK_DISABLE();
#define TIM_CNT_PIN   PA0
#define TIM_CNT_AF    GPIO_AF1_TIM2

#define TIM_CNT2 TIM3
#define TIM_CNT2_EN    __HAL_RCC_TIM3_CLK_ENABLE();
#define TIM_CNT2_DIS   __HAL_RCC_TIM3_CLK_DISABLE();
#define TIM_CNT2_PIN   PD2
#define TIM_CNT2_AF    GPIO_AF2_TIM3

#define TIM_PWM TIM5
#define TIM_PWM_EN    __HAL_RCC_TIM5_CLK_ENABLE();
#define TIM_PWM_DIS   __HAL_RCC_TIM5_CLK_DISABLE();
#define TIM_PWM_PIN   PA1
#define TIM_PWM_AF    GPIO_AF2_TIM5
#define TIM_PWM_CHANNEL TIM_CHANNEL_2
#define PWM_CCR CCR2

#endif

