#ifndef _LOCAL_HAL_CONF_H
#define _LOCAL_HAL_CONF_H

#define HX711_SCK_GPIO GpioC
#define HX711_SCK_PIN  10
#define HX711_DAT_GPIO GpioC
#define HX711_DAT_PIN  11

#define UART_MODBUS USART1
#define UART_MODBUS_CLK_ENABLE __HAL_RCC_USART1_CLK_ENABLE
#define UART_MODBUS_GPIO GpioA
#define UART_MODBUS_GPIO_PINS ( BIT9 | BIT10 )
#define UART_MODBUS_GPIO_AF GPIO_AF7_USART1
#define UART_MODBUS_IRQ USART1_IRQn
#define UART_MODBUS_IRQHANDLER USART1_IRQHandler

#define HAL_UART_USERINIT_FUN HAL_UART_UserInit

int MX_MODBUS_UART_Init(void);

#define TIM_CNT TIM2
#define TIM_CNT_EN    __HAL_RCC_TIM2_CLK_ENABLE();  __HAL_RCC_GPIOA_CLK_ENABLE();
#define TIM_CNT_DIS   __HAL_RCC_TIM2_CLK_DISABLE();
#define TIM_CNT_PINNUM 0
#define TIM_CNT_PIN   ( 1 << TIM_CNT_PINNUM )
#define TIM_CNT_AF    GPIO_AF1_TIM2
#define TIM_CNT_GPIO  GpioA

#define TIM_CNT2 TIM3
#define TIM_CNT2_EN    __HAL_RCC_TIM3_CLK_ENABLE();  __HAL_RCC_GPIOD_CLK_ENABLE();
#define TIM_CNT2_DIS   __HAL_RCC_TIM3_CLK_DISABLE();
#define TIM_CNT2_PINNUM 2
#define TIM_CNT2_PIN   ( 1 << TIM_CNT2_PINNUM )
#define TIM_CNT2_AF    GPIO_AF2_TIM3
#define TIM_CNT2_GPIO  GpioD

#define TIM_PWM TIM5
#define TIM_PWM_EN    __HAL_RCC_TIM5_CLK_ENABLE();  __HAL_RCC_GPIOA_CLK_ENABLE();
#define TIM_PWM_DIS   __HAL_RCC_TIM5_CLK_DISABLE();
#define TIM_PWM_PIN   GPIO_PIN_1
#define TIM_PWM_AF    GPIO_AF2_TIM5
#define TIM_PWM_GPIO  GpioA
#define TIM_PWM_CHANNEL TIM_CHANNEL_2
#define PWM_CCR CCR2

#endif

